name: flutter_dropzone_web
description: A drag-and-drop Flutter plugin (Web only).
version: 4.0.1
homepage: https://github.com/deakjahn/flutter_dropzone

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_dropzone_platform_interface: ^2.0.6
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  flutter_dropzone_platform_interface:
    path: ../flutter_dropzone_platform_interface

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterDropzonePlugin
        fileName: flutter_dropzone_plugin.dart

  assets:
    - packages/flutter_dropzone_web/assets/flutter_dropzone.js